### ISSUE TITLE
Report by category - app "remembering the previous period?

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#33]
Hi
I have just noticed a strange behaviour.
In February I set the report "by category" with a filter to "this month". So it was showing February's data.
Now we are on march 2nd. The report still shows the data of February,. See screenshots attached even thought the filter is set as before to "this month". So it seems that there's is a big that the period is saved wrongly and not updated after the month changes 
For curiosity I chanede now the filter to "this month" and resablved and now the march is visible.
So there must be a bug that the period is not relative but absolute. I'm this is a new bug, haven't sent it before in the last 12 years.
Can you investigate?
Thanks 
![Screenshot_20240302-174342](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/fed975ac-b500-44fa-a4a1-b9657c23a2cc)
![Uploading Screenshot_20240302-174404.png…]()

**Comment by secco-online** [comment]
![Screenshot_20240302-174404](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/4539e2d8-d2a9-4dc1-9d7b-82b5954241b7)

**Comment by tiberiusteng** [comment]
It should be always this way, the exact time of start/end of period is determined when you selected the "This Month" option. I just fixed how it works when selecting the period in blotter filter, but seems I've missed the report part ... I'll change it to automatically update each time opening the report view later.

**Comment by secco-online** [comment]
Thanks for fixing

**Comment by secco-online** [comment]
unfortunatelly solved. You changed the part that is responsible for showing the date rqnde on top of the screen (I highlighted it in the attached screenshot) but not the dates that are responsible for extracting data for the selected period.
Please verify. Thanks 
![Screenshot_20240306-122450](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/1f473774-3b88-4164-8df1-1c38ae003a04)

**Comment by tiberiusteng** [comment]
What's the flow you take to arrive at this state? You selected "this week" on the last week, and today you selected "By Category" report from main screen / report tab, and it shows the date of this week and the report content is last week?

**Comment by secco-online** [comment]
Hi. I noticed the same bug on the "budget" screen. My monthly budgets are still showing the data form February even though we are well in march. Shall I open a new issue or we manage it here together with reports' filtering problem ?
![Screenshot_20240308-055126](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/e94875b3-9c1e-470e-8b26-ce78f33b375e)
![Screenshot_20240308-055144](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/832d8698-259a-414f-96a3-d067f61ebafb)

**Comment by tiberiusteng** [comment]
Just leave it here, I'll fix them together.

**Comment by secco-online** [comment]
Resolved in version 2024-03-11. Thanks
